import org.junit.Test;

import sample.SampleApplication;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'goo4680' at '3/1/17 2:49 PM' with Gradle 2.14.1
 *
 * @author goo4680, @date 3/1/17 2:49 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
      //  assertTrue("someLibraryMethod should return 'true'", SampleApplication.dummy());
      //  assertTrue( SampleApplication.dummy());
        
    }
}
