/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'goo4680' at '3/1/17 2:49 PM' with Gradle 2.14.1
 *
 * @author goo4680, @date 3/1/17 2:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
